# Generated by Django 5.1.1 on 2024-09-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_absents', related_query_name='my_absents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absent',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_absents', related_query_name='sub_absents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absent',
            name='absent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', related_query_name='absents', to='absent.absenttype'),
        ),
    ]
