# Generated by Django 5.1.1 on 2024-09-10 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', related_query_name='staffs', to='oaauth.oadepartment'),
        ),
    ]
